### ISSUE TITLE
Update design

### ISSUE THREAD

**Issue by marti1125** [mozillahispano/asksumo-fb#45]
please use this reference: https://www.mozilla.org/en-US/styleguide/

**Comment by marti1125** [comment]
commit  b00ec5d

**Comment by marti1125** [comment]
@nukeador could you push this to production?

**Comment by nukeador** [comment]
Apparently this is updated. I can't check this more deeply right now.

@stripTM @willyaranda The script is located here /root/bin/fbrumbo-update and should be in the cron. Apparently repo is already up-to-date.

**Comment by marti1125** [comment]
ok, @nukeador thanks a lot 👍
